# Generated by Django 4.2.16 on 2025-12-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerabout',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='store_banners/'),
        ),
        migrations.AddField(
            model_name='sellerabout',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerabout',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
        migrations.AddField(
            model_name='sellerabout',
            name='phone_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerabout',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
