# Generated by Django 4.2.16 on 2025-11-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('shipping_address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('delivery_option', models.CharField(max_length=100)),
                ('checkout_price', models.BigIntegerField()),
                ('order_status', models.CharField(default='pending', max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('time', models.BigIntegerField()),
            ],
        ),
    ]
