# Generated by Django 4.2.16 on 2025-12-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagepath',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='imagepath',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
