# Generated by Django 4.2.16 on 2025-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
