# Generated by Django 4.2.16 on 2025-12-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
